### ISSUE TITLE
constexpr is not compiled

### ISSUE THREAD

**Issue by SuminHan** [Fobbah/bwsal#37]
It seems C++ 11 in VS2013 does not support constexpr, and it makes tons of errors.
ref: https://msdn.microsoft.com/en-us/library/hh567368(v=vs.120).aspx
I tried with VS2015 or VS2017, and they support constexpr, but has error with linker version.
Is there any way to solve my problem?

**Comment by dgant** [comment]
You could upgrade to BWAPI 4.2 and be able to use VS2017. You'll need to compile your own BWAPI.lib as well but that should (hopefully) be straightforward.

**Comment by SuminHan** [comment]
Thanks, i solved the problem by compiling BWAPI by my own.
